# Generated by Django 4.1.12 on 2023-10-10 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gms_backend", "0002_blog1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="Blog1",
        ),
    ]
