# Generated by Django 4.1.12 on 2023-10-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gms_backend", "0003_delete_blog_delete_blog1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tagline", models.TextField()),
            ],
            options={
                "managed": True,
            },
        ),
    ]
