# Generated by Django 4.1.12 on 2023-10-10 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gms_backend", "0004_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
