# Generated by Django 4.1.12 on 2023-10-10 08:50

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gms_backend", "0005_delete_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("mobile_number", models.CharField(max_length=15)),
                ("age", models.IntegerField()),
                ("dob", models.DateField(blank=True, null=True)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DiabetiesInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("TYPE 1", "TYPE 1"), ("TYPE 2", "TYPE 2")],
                        max_length=20,
                    ),
                ),
                ("notes", djongo.models.fields.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gms_backend.user",
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
    ]
