# Generated by Django 4.1.12 on 2023-10-16 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gms_backend", "0006_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiabetiesInfo",
        ),
    ]
