# Generated by Django 4.1.12 on 2023-10-10 09:03

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("gms_backend", "0007_alter_diabetiesinfo_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diabetiesinfo",
            name="notes",
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
